TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

# Configuration data files are installed in $TOP)/data
DATA += procserv-pr_mk.service
DATA += prplc.cfg

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

